### ISSUE TITLE
How to use the code?

### ISSUE THREAD

**Issue by robouden** [toowaki/yFlowGen#3]
Thanks for creating this software. I could not find the .exe file and I tried to run after renaming the files, but I do not understand what to change in the filenames to make it run. Can you explain a bit more?

Regards,
Rob Oudendijk

**Comment by toowaki** [comment]
Dear Rob,

I understand that it's a little strange. 
The English version may be fine as is as an exe.

Japanese company PCs may block downloads of files from outside the company just because they have an .exe extension. 

For this reason, I use the extension ex_. I then asked the user to change the extension to exe. 

I did this because the main users of this software are Japanese companies that use the C language.

**Comment by toowaki** [comment]
Previously, it had the .exe extension .ex_, but from V5.0 it is provided as .exe.
